#######################################################
# 
# BrokenLine.py
# Python implementation of the Class BrokenLine
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:52:25
# Original author: User
# 
#######################################################
import LineSegment

class BrokenLine:
    m_LineSegment= LineSegment()

    def draw() -> void:
        pass

    def get_number_of_points() -> int:
        pass

    def set_number_of_points(number : int) -> void:
        pass