#######################################################
# 
# BrokenLine.py
# Python implementation of the Class BrokenLine
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:52:25
# Original author: User
# 
#######################################################
from shapes.LineSegment import LineSegment
from shapes.OpenFigure import OpenFigure


class BrokenLine(OpenFigure):

    def __init__(self, border_color, inner_points):
        super().__init__(
            border_color=border_color,
            start_point=inner_points[0],
            end_point=inner_points[-1]
        )
        self._inner_points = inner_points

    inner_points = property()

    @inner_points.getter
    def inner_points(self):
        return self._inner_points

    @inner_points.setter
    def inner_points(self, value):
        # NOTE: update start and end point
        self.start_point = value[0]
        self.end_point = value[-1]
        self._inner_points = value

    def draw(self, qp):
        qp.setPen(self.pen)
        qp.drawPolyline(*self.inner_points)

    def move(self, shift):
        for point in self.inner_points:
            point += shift
        self.start_point = self.inner_points[0]
        self.end_point = self.inner_points[-1]
