#######################################################
# 
# BrokenLine.py
# Python implementation of the Class BrokenLine
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:52:25
# Original author: User
# 
#######################################################
from shapes.LineSegment import LineSegment


class BrokenLine:

    def draw(self):
        pass

    def get_number_of_points(self) -> int:
        pass

    def set_number_of_points(self,number: int):
        pass
