#######################################################
# 
# Circle.py
# Python implementation of the Class Circle
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:52:44
# Original author: User
# 
#######################################################
import Ellipse

class Circle(Ellipse):
    def draw() -> void:
        pass