#######################################################
# 
# Circle.py
# Python implementation of the Class Circle
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:52:44
# Original author: User
# 
#######################################################
from shapes.Ellipse import Ellipse


class Circle(Ellipse):
    def draw(self):
        pass
