#######################################################
# 
# CloseFigure.py
# Python implementation of the Class CloseFigure
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:52:48
# Original author: User
# 
#######################################################
from shapes.Figure import Figure


class CloseFigure(Figure):
    def get_inner_color(self):
        pass

    def set_inner_color(self):
        pass
