#######################################################
# 
# CloseFigure.py
# Python implementation of the Class CloseFigure
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:52:48
# Original author: User
# 
#######################################################
from shapes.Figure import Figure
from helpers.constants import DefaultDrawParams

class CloseFigure(Figure):

    def __init__(self, center_point, border_color, inner_color=DefaultDrawParams.inner_color):
        super().__init__(center_point, border_color)
        self._inner_color = inner_color

    def get_inner_color(self):
        pass

    def set_inner_color(self):
        pass
