#######################################################
# 
# CloseFigure.py
# Python implementation of the Class CloseFigure
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:52:48
# Original author: User
# 
#######################################################
import Figure

class CloseFigure(Figure):
    def get_inner_color() -> Color:
        pass

    def set_inner_color(color : Color) -> void:
        pass