#######################################################
# 
# Ellipse.py
# Python implementation of the Class Ellipse
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:52:52
# Original author: User
# 
#######################################################
from helpers.geometry import get_distance
from shapes.CloseFigure import CloseFigure


class Ellipse(CloseFigure):

    @property
    def top_point(self):
        return self._top_point

    @property
    def left_point(self):
        return self._left_point

    def __init__(self, border_color, inner_color, center_point, left_point, top_point):
        super().__init__(
            center_point=center_point,
            border_color=border_color,
            inner_color=inner_color,
        )
        self.left_point = left_point
        self.top_point = top_point

    @left_point.getter
    def left_point(self):
        return self._left_point

    @left_point.setter
    def left_point(self, value):
        self._left_point = value

    @top_point.getter
    def top_point(self):
        return self._top_point

    @top_point.setter
    def top_point(self, value):
        self._top_point = value

    def draw(self, qp):
        qp.setPen(self.pen)
        qp.setBrush(self._inner_color)
        radius_x = get_distance(self.center_point, self.left_point)
        radius_y = get_distance(self.center_point, self.top_point)
        qp.drawEllipse(self._center_point, radius_x, radius_y)

    def move(self, shift):
        self.center_point += shift
        self.left_point += shift
        self.top_point += shift
