#######################################################
# 
# Ellipse.py
# Python implementation of the Class Ellipse
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:52:52
# Original author: User
# 
#######################################################
import CloseFigure

class Ellipse(CloseFigure):
    def draw() -> void:
        pass

    def get_left_point() -> Point:
        pass

    def get_top_point() -> Point:
        pass

    def set_left_point(point : Point) -> void:
        pass

    def set_top_point(point : Point) -> void:
        pass