#######################################################
# 
# Figure.py
# Python implementation of the Class Figure
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:53:03
# Original author: User
# 
#######################################################
from shapes.Point import Point


class Figure:
    def draw(self):
        pass

    def get_color(self) -> str:
        pass

    def get_point(self) -> Point:
        pass

    def location(self):
        pass

    def move(self):
        pass

    def set_color(self, color: str):
        pass

    def set_point(self, point):
        pass
