#######################################################
# 
# Figure.py
# Python implementation of the Class Figure
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:53:03
# Original author: User
# 
#######################################################
from shapes.Point import Point
from helpers.constants import DefaultDrawParams
from PyQt5.QtGui import QPen


class Figure:
    def __init__(self, center_point=None, border_color=DefaultDrawParams.pen_color):
        self._center_point = center_point
        self._border_color = border_color

    def draw(self):
        pass

    def get_color(self) -> str:
        pass

    def get_point(self) -> Point:
        pass

    def location(self):
        pass

    def move(self):
        pass

    def set_color(self, color: str):
        pass

    def set_point(self, point):
        pass

    @property
    def pen(self):
        """create and return default pen"""
        pen = QPen()
        pen.setStyle(DefaultDrawParams.pen_style)
        pen.setWidth(DefaultDrawParams.pen_thickness)
        pen.setBrush(self._border_color)
        pen.setCapStyle(DefaultDrawParams.pen_cap_style)
        pen.setJoinStyle(DefaultDrawParams.pen_join_style)
        return pen
