#######################################################
# 
# Figure.py
# Python implementation of the Class Figure
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:53:03
# Original author: User
# 
#######################################################


class Figure:
    def draw() -> void:
        pass

    def get_color() -> str:
        pass

    def get_point() -> Point:
        pass

    def location() -> void:
        pass

    def move() -> void:
        pass

    def set_color(color : str) -> void:
        pass

    def set_point(point : Point) -> void:
        pass