#######################################################
# 
# IrregularPolygon.py
# Python implementation of the Class IrregularPolygon
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:53:11
# Original author: User
# 
#######################################################
import Polygon

class IrregularPolygon(Polygon):
    def draw() -> void:
        pass