#######################################################
# 
# IrregularPolygon.py
# Python implementation of the Class IrregularPolygon
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:53:11
# Original author: User
# 
#######################################################
from shapes.Polygon import Polygon


class IrregularPolygon(Polygon):
    def draw(self):
        pass
