#######################################################
# 
# IsoscelesTriangle.py
# Python implementation of the Class IsoscelesTriangle
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:53:16
# Original author: User
# 
#######################################################
import Triangle

class IsoscelesTriangle(Triangle):
    def draw() -> void:
        pass