#######################################################
# 
# LineSegment.py
# Python implementation of the Class LineSegment
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:53:34
# Original author: User
# 
#######################################################
import OpenFigure

class LineSegment(OpenFigure):
    def draw() -> void:
        pass