#######################################################
# 
# LineSegment.py
# Python implementation of the Class LineSegment
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:53:34
# Original author: User
# 
#######################################################
from shapes.OpenFigure import OpenFigure

class LineSegment(OpenFigure):
    def draw(self):
        pass