#######################################################
# 
# LineSegment.py
# Python implementation of the Class LineSegment
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:53:34
# Original author: User
# 
#######################################################
from shapes.OpenFigure import OpenFigure


class LineSegment(OpenFigure):
    def draw(self, qp):
        qp.setPen(self.pen)
        qp.drawLine(self.start_point, self.end_point)

    def move(self, shift):
        self.start_point += shift
        self.end_point += shift
