#######################################################
# 
# Line.py
# Python implementation of the Class Line
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:53:23
# Original author: User
# 
#######################################################
import Ray

class Line(Ray):
    def draw() -> void:
        pass