#######################################################
# 
# OpenFigure.py
# Python implementation of the Class OpenFigure
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:54:07
# Original author: User
# 
#######################################################
import Figure

class OpenFigure(Figure):
    def get_end_point() -> Point:
        pass

    def get_start_point() -> Poit:
        pass

    def set_end_point(point : Point) -> void:
        pass

    def set_start_point(point : Point) -> void:
        pass