#######################################################
# 
# OpenFigure.py
# Python implementation of the Class OpenFigure
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:07
# Original author: User
# 
#######################################################
from shapes.Figure import Figure
from shapes.Point import Point


class OpenFigure(Figure):
    def get_end_point(self) -> Point:
        pass

    def get_start_point(self) -> Point:
        pass

    def set_end_point(point : Point):
        pass

    def set_start_point(point : Point):
        pass