#######################################################
# 
# Parallelogram.py
# Python implementation of the Class Parallelogram
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:11
# Original author: User
# 
#######################################################
import Quadrilateral
from shapes.Point import Point


class Parallelogram(Quadrilateral):
    def draw(self):
        pass

    def location(self) -> Point:
        pass

    def move(self):
        pass