#######################################################
# 
# Parallelogram.py
# Python implementation of the Class Parallelogram
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:54:11
# Original author: User
# 
#######################################################
import Quadrilateral

class Parallelogram(Quadrilateral):
    def draw() -> void:
        pass

    def location() -> Point:
        pass

    def move() -> void:
        pass