#######################################################
# 
# Point.py
# Python implementation of the Class Point
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:16
# Original author: User
# 
#######################################################


class Point:

    def get_x(self) -> float:
        pass

    def get_y(self) -> float:
        pass

    def set_x(self):
        pass

    def set_y(self):
        pass
