#######################################################
# 
# Point.py
# Python implementation of the Class Point
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:54:16
# Original author: User
# 
#######################################################
import Figure

class Point:
    m_Figure= Figure()

    def get_x() -> float:
        pass

    def get_y() -> float:
        pass

    def set_x(x : float) -> void:
        pass

    def set_y(y : float) -> void:
        pass