#######################################################
# 
# Polygon.py
# Python implementation of the Class Polygon
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:54:25
# Original author: User
# 
#######################################################
import CloseFigure

class Polygon(CloseFigure):
    def draw() -> void:
        pass

    def get_points() -> Point[1..*]:
        pass

    def set_points(points : Point[1..*]) -> void:
        pass