#######################################################
# 
# Polygon.py
# Python implementation of the Class Polygon
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:25
# Original author: User
# 
#######################################################
from shapes.CloseFigure import CloseFigure


class Polygon(CloseFigure):
    def draw(self):
        pass

    def get_points(self):
        pass

    def set_points(self, points):
        pass
