#######################################################
# 
# Quadrilateral.py
# Python implementation of the Class Quadrilateral
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:54:29
# Original author: User
# 
#######################################################
import Polygon

class Quadrilateral(Polygon):
    def draw() -> void:
        pass