#######################################################
# 
# Ray.py
# Python implementation of the Class Ray
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:34
# Original author: User
# 
#######################################################
from shapes.LineSegment import  LineSegment

class Ray(LineSegment):
    def draw(self):
        pass