#######################################################
# 
# Ray.py
# Python implementation of the Class Ray
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:34
# Original author: User
# 
#######################################################
from shapes.LineSegment import LineSegment
from helpers.geometry import get_line_point


class Ray(LineSegment):

    def __init__(self, border_color, start_point, end_point, border):
        super().__init__(
            start_point=start_point,
            end_point=get_line_point(start_point, end_point, x=border.bottomRight().x()),
            border_color=border_color,
        )