#######################################################
# 
# Rectangle.py
# Python implementation of the Class Rectangle
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:42
# Original author: User
# 
#######################################################
import Quadrilateral

class Rectangle(Quadrilateral):
    def draw(self):
        pass