#######################################################
# 
# Rectangle.py
# Python implementation of the Class Rectangle
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:42
# Original author: User
# 
#######################################################
from PyQt5.QtCore import QPoint

from shapes.Polygon import Polygon


class Rectangle(Polygon):

    def __init__(
            self, left_bottom_point, right_upper_point, border_color=None, inner_color=None
    ):
        super().__init__(
            border_color=border_color,
            inner_color=inner_color,
            border_points=[
                left_bottom_point, QPoint(left_bottom_point.x(), right_upper_point.y()),
                right_upper_point, QPoint(right_upper_point.x(), left_bottom_point.y())
            ]
        )