#######################################################
# 
# RegularPolygon.py
# Python implementation of the Class RegularPolygon
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:54:48
# Original author: User
# 
#######################################################
import Polygon

class RegularPolygon(Polygon):
    def draw() -> void:
        pass

    def get_number_of_sides() -> int:
        pass

    def set_number_of_sides(number : int) -> void:
        pass