#######################################################
# 
# RegularPolygon.py
# Python implementation of the Class RegularPolygon
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:48
# Original author: User
# 
#######################################################
from shapes.Polygon import Polygon

class RegularPolygon(Polygon):
    def draw(self):
        pass

    def get_number_of_sides(self) -> int:
        pass

    def set_number_of_sides(number : int):
        pass