#######################################################
# 
# Rhombus.py
# Python implementation of the Class Rhombus
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:54:53
# Original author: User
# 
#######################################################
from PyQt5.QtCore import QPoint

from shapes.Polygon import Polygon


class Rhombus(Polygon):

    def __init__(
            self, top_point, left_point, border_color=None, inner_color=None
    ):
        super().__init__(
            border_color=border_color,
            inner_color=inner_color,
            border_points=[
                top_point, left_point,
                QPoint(top_point.x(), 2 * left_point.y() - top_point.y()),
                QPoint(2 * top_point.x() - left_point.x(), left_point.y())
            ]
        )
