#######################################################
# 
# Rhombus.py
# Python implementation of the Class Rhombus
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:54:53
# Original author: User
# 
#######################################################
import Quadrilateral

class Rhombus(Quadrilateral):
    def draw() -> void:
        pass