#######################################################
# 
# RightTriangle.py
# Python implementation of the Class RightTriangle
# Generated by Enterprise Architect
# Created on:      17-фев-2021 17:54:58
# Original author: User
# 
#######################################################
import Triangle

class RightTriangle(Triangle):
    def draw() -> void:
        pass