#######################################################
# 
# Triangle.py
# Python implementation of the Class Triangle
# Generated by Enterprise Architect
# Created on:      17-���-2021 17:55:03
# Original author: User
# 
#######################################################
import Polygon


class Triangle(Polygon):
    def draw(self):
        pass
